server:
  port: ${SERVER_PORT:8080}

spring:
  jmx:
    enabled: false
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}"

  output:
    ansi:
      enabled: ALWAYS