spring:
  application:
    name: ${SPRING_APPLICATION_NAME:msvc-product}
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}"
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLED:ALWAYS}
  

