
server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: msvc-order
  output:
    ansi:
      enabled: ALWAYS  
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}"
